### PR TITLE
Nuget.exe

### PR DESCRIPTION
**Pull request by frenzqse**

### CODE REVIEW

**Comment by kristofmeixner** [comment]
Hmm... wouldn't make a rebase more sense as the bin is still in git?

**Comment by frenzqse** [comment]
In this situation, I think it is better to show the single steps. It shows which files has to be changed to remove the neget.exe. WDYT?

Could you please send the link to the bin folder? I do not find one in this project and in git.

**Comment by anpieber** [comment]
https://github.com/openengsb/loom-csharp/tree/master/bridge/.nuget

**Comment by kristofmeixner** [comment]
Clear steps sure but if you're doing like that the exe will remain in the history/git repo

**Comment by anpieber** [comment]
yeah well better that than a force push. dont u think?

**Comment by kristofmeixner** [comment]
Sorry I thougt the exe was just recently added but just realized it's about 6 moths within the repo.

**Comment by anpieber** [comment]
NP :-)

**Comment by frenzqse** [comment]
ok :-).
the .nuget folder has to be present because of the .nuget/nuget.target. This file contains the parameters for downloading the nuget.exe
https://github.com/frenzqse/loom-csharp/blob/NewStruture/bridge/.nuget/NuGet.targets

**Pull request merged**
