### PR TITLE
[OPENENGSB-3639] Not all the dlls are copied to the outputdirectory (.Ne...

### PR DESCRIPTION
**Pull request by frenzqse**
...t Bridge)

### CODE REVIEW

**Comment by anpieber** [comment]
why are they copied now?

**Comment by frenzqse** [comment]
@y I did a mistake on Nuget, so I had to increase one more. (It is not possible to override/delete a package on nuget)

**Comment by frenzqse** [comment]
Which line do you mean with "why are they copied now?"

**Comment by anpieber** [comment]
NP, was just curious about the version number. Well the comment says: "Not all the dlls are copied to the outputdirectory (.Ne..." I'm trying to see why those dlls are copied now?

**Comment by frenzqse** [comment]
It is a little bit difficult to explain. This is an issue, which only occurs in a special case.

My idea of the factory was, it search through all the refereed assemblies in the project and searches the corresponding openengsb dll implementation (For example Openengsb300). However, Openengsb300 is never used concrete in the code (i.e new openengsb300.Connectionfactory()). Very often, when the .Net project is added to a library project and this project is also executed. In this case the Openengsb300 dll is in the outputdirectory and can be accessed over reflection.

The issue occurs when the library project (contains the .Net Bridge libraries) is added as a library to an other project. Then .Net optimize the code and finds out that the Openengsb300 is never used and don't copie the dll to the output directory. It follows that the dll can not be accessed over reflection.

**Comment by frenzqse** [comment]
Now the dlls are used because, OpenEngSB300.SetSupport() can be invoked and then the OpenEngSB300 is referenced once and so added to the output directory.

**Pull request merged**
